### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by FliccLmao** [agraubert/Beymax#97]
When i try to startup the bot with python main.py it shows this error

C:\Users\Rohan\Downloads\Pog Stuff\The Dogester>python main.py
C:\Users\Rohan\Downloads\Pog Stuff\The Dogester\bots\core.py:37: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.configuration = yaml.load(reader)
Traceback (most recent call last):
  File "C:\Users\Rohan\Downloads\Pog Stuff\The Dogester\main.py", line 192, in <module>
    bey = ConstructBeymax()
  File "C:\Users\Rohan\Downloads\Pog Stuff\The Dogester\main.py", line 57, in ConstructBeymax
    beymax = CoreBot()
  File "C:\Users\Rohan\Downloads\Pog Stuff\The Dogester\bots\core.py", line 38, in __init__
    self.command_prefix = self.config_get('prefix', default='!')
  File "C:\Users\Rohan\Downloads\Pog Stuff\The Dogester\bots\core.py", line 345, in config_get
    if key in obj:
TypeError: argument of type 'NoneType' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rohan\Downloads\Pog Stuff\The Dogester\main.py", line 195, in <module>
    print(bey._dbg_event_queue)
NameError: name 'bey' is not defined

**Comment by agraubert** [comment]
What does your `config.yml` look like? This kind of sounds like it's being parsed as a `None` object instead of a dictionary

**Comment by agraubert** [comment]
I'm going to close this issue as I haven't heard from you in a while. If you still need help, please feel free to reopen this issue.
